# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
- name: tag
  value: '$(Build.BuildId)'
- name: password_cert
  value: MyPassword
- name: environment
  value: Deployment
- name: docker-repo
  value: minhman1504

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    # pool: 
    #  name: 'dotnet-agent-pool'
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          # Write your PowerShell commands here.
          dotnet dev-certs https -ep ./https/weatherapi.pfx -p $(password_cert)
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerHubRegistry'
        repository: '$(docker-repo)/dotnet-image'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
         $(tag)
        arguments: --build-arg PASSWORD_CERT=$(password_cert) --build-arg ENVIRONMENT=$(environment)
    # - task: Docker@2
    #   displayName: Build an image
    #   inputs:
    #     command: build
    #     dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    #     repository: dotnet-image
    #     tags: |
    #      $(tag)
    #     arguments: --build-arg PASSWORD_CERT=$(password_cert) --build-arg ENVIRONMENT=$(environment)
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: 'docker images'
    # - task: Docker@2
    #   inputs:
    #     containerRegistry: 'DockerHubRegistry'
    #     repository: 'dotnet-image'
    #     command: 'push'
